# Generated by Django 6.0.3 on 2026-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор сессии оплаты в Stripe",
                max_length=255,
                null=True,
                verbose_name="ID сессии Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("cash", "Наличными"),
                    ("bank", "Перевод на счёт"),
                    ("card", "Банковская карта"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
